[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@rdubois-crypto/FreshCryptoLib=lib/FreshCryptoLib/solidity/src/",
    "@account-abstraction/contracts=lib/account-abstraction/contracts/",
    "@safe-global/safe-contracts/contracts=lib/safe-contracts/contracts/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
